pkgbump: support different files, use absolute paths
- allow the file to check to be set using the first argument,
- try package.json and server/package.json if the argument isn't set
- bail out if the file does not exist
- prefix all files with the git root dir

diff --git a/pkgbump b/pkgbump
--- a/pkgbump
+++ b/pkgbump
@@ -11,12 +11,33 @@ print_patch() {
   awk -F '.' '/version/{print $3+0}'
 }
 
-MASTER="$(git show origin/master:package.json | print_patch)";
-CURRENT="$(cat package.json | print_patch)";
+# The file that contains the version number
+FILE=${FILE:-}
+
+ROOT="$(git rev-parse --show-toplevel)"
+
+# If file is not set and try to find it
+if [[ -z "$FILE" ]]; then
+  for file in "package.json" "server/package.json"; do
+    if [[ -f "$ROOT/$file" ]]; then
+      FILE="$file"
+      break
+    fi
+  done
+fi
+
+if [[ -f "$FILE" ]]; then
+  echo "could not find package.json file, please check/set FILE variable"
+  exit 1
+fi
+
+
+MASTER="$(git show origin/master:$FILE | print_patch)";
+CURRENT="$(cat "$ROOT/$FILE" | print_patch)";
 
 git fetch origin master
 if [[ $MASTER -ge $CURRENT ]]; then
-  perl -i -pe 's/(version": "(\d+\.)*)(\d+)(.*)/$1.($3+1).$4/e' package.json
-  git commit package.json --no-verify -m "bump version" > /dev/null
+  perl -i -pe 's/(version": "(\d+\.)*)(\d+)(.*)/$1.($3+1).$4/e' "$ROOT/$FILE"
+  git commit "$ROOT/$FILE" --no-verify -m "bump version" > /dev/null
   echo "bumped and commited patch version"
 fi
